name: Hourly API Call
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: curl https://weather-hub-test.vercel.app/api/send-email
